language: python

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run flake8 pylint_topology
